name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # O la versión que prefieras

      # Instalar dependencias necesarias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Convertir y ejecutar el archivo Jupyter Notebook como script
      - name: Run Jupyter Notebook
        run: |
          pip install nbconvert
          jupyter nbconvert --to script Arango_Andres_Analizando_EA1.ipynb
          python Arango_Andres_Analizando_EA1.ipynb

      # Ejecutar pruebas automatizadas con pytest
      - name: Run tests
        run: |
          pip install pytest
          pytest tests/

      # Opcional: Despliegue continuo
      - name: Deploy
        run: |
          echo "Aquí puedes añadir tus scripts de despliegue"
          echo "Por ejemplo, usar AWS CLI, Docker, u otros sistemas"
